bogusfile.conf was hard coded in python worker error msg
Whops!  bogusfile.conf was hardcoded, so the error message was wrong:

    $ ./workerTestBasic.py test-basic.conf
    Traceback (most recent call last):
      File "./workerTestBasic.py", line 138, in <module>
        worker = WorkerTestBasicPython(sys.argv[1])
      File "./workerTestBasic.py", line 24, in __init__
        super(WorkerTestBasicPython, self).__init__(cfg)
      File "/usr/lib/python2.6/site-packages/gearbox.py", line 765, in
    __init__
        raise IOError("config file '%s' is not a file" % config)
    IOError: config file 'bogusfile.conf' is not a file

Now the error message properly displays the filename the user provided.