use strcpy instead of std::strcpy
After downgrading boost I started getting this error when compiling
the python swig bindings:

    error: 'strcpy' is not a member of 'std'

strcpy is defined in string.h, std::strcpy is from cstring.h

I want the one from string.h