fix test to work with gearbox > 1.1
The version of gearbox in the EPEL is 1.1.8.  A gearbox test,
workers/t/gearbox/put-job.t, fails to compile because of a
namespacing issue:

 In file included from /usr/include/libgearman-1.0/worker.h:47,
                  from /usr/include/libgearman-1.0/gearman.h:102,
                  from /usr/include/libgearman/gearman.h:40,
                  from common/stub/gearman.hh:2,
                  from workers/t/gearbox/put-job.t.cc:21:
 libgearman-1.0/interface/worker.h:52: error: reference to ‘Worker’ is ambiguous
 libgearman-1.0/interface/worker.h:41: error: candidates are: struct Worker
 ./gearbox/worker/Worker.h:28: error:                 class Gearbox::Worker

This is easily resolved by using fully qualified names.