Need to ensure supervise is done for cleanup.
o During delete of gearbox or gearbox-test-workers services, it does a
  "svc -dx" followed by "rm -rf" which fails occasionally (see below for
  details on rm -rf does not work always). To address this, a check if
  supervise is no longer running is added via the svok system call.
o If install is immediately followed by uninstall, cleanup fails
  sometimes since supervise has not started yet. In that case, we now
  wait for 5 secs to allow supervise to run.

Error seen from gearbox-svc-builder
rm: cannot remove `/var/gearbox/gearbox-workers/gearbox-sync-worker-04/log/supervise': Directory not empty
ERROR: rm -rf /var/gearbox/gearbox-workers/gearbox-sync-worker-04

$ rm -ri rmtest
rm: descend into directory `rmtest'? y
rm: remove directory `rmtest/foo'? y
rm: remove directory `rmtest/bar'? ^Z
[1]+  Stopped                 rm -ri rmtest
[EXIT 148] $ mkdir -p rmtest/baz
$ fg
rm -ri rmtest
y
rm: remove directory `rmtest'? y
rm: cannot remove `rmtest': Directory not empty
$